name: CI
on:
  push:
    branches: ['*']
  pull_request:
    branches: [master]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: gradle assemble
      - name: Build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/libs/*.jar
  test:
    name: test
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Export profile active
        run: export SPRING_PROFILES_ACTIVE=local
      - uses: actions/checkout@v2
      - name: Testing
        run: gradle check --stacktrace
      - name: Test report upload
        uses: actions/upload-artifact@v2
        with:
          name: Test report
          path: build/reports/jacoco/*
      - name: Print result
        run: cat build/reports/jacoco/test/html/index.html | grep -o '<tfoot>.*</tfoot>'
